/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhCalendar: typeof import('~icons/ph/calendar')['default']
    IPhClock: typeof import('~icons/ph/clock')['default']
    IPhEnvelope: typeof import('~icons/ph/envelope')['default']
    IPhGlobe: typeof import('~icons/ph/globe')['default']
    IPhIdentificationCardThin: typeof import('~icons/ph/identification-card-thin')['default']
    IPhListHeart: typeof import('~icons/ph/list-heart')['default']
    IPhMinus: typeof import('~icons/ph/minus')['default']
    IPhMinusCircle: typeof import('~icons/ph/minus-circle')['default']
    IPhPaperPlane: typeof import('~icons/ph/paper-plane')['default']
    IPhPencil: typeof import('~icons/ph/pencil')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhPresentationChart: typeof import('~icons/ph/presentation-chart')['default']
    IPhRocketLaunch: typeof import('~icons/ph/rocket-launch')['default']
    IPhSignOut: typeof import('~icons/ph/sign-out')['default']
    IPhTrash: typeof import('~icons/ph/trash')['default']
    IPhUpload: typeof import('~icons/ph/upload')['default']
    IPhUserCircle: typeof import('~icons/ph/user-circle')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    ResumeUpload: typeof import('./../components/ResumeUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
